# Oh My Zsh
export ZSH="/home/oscar/.oh-my-zsh"
ZSH_THEME="spaceship"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# User configuration
export LANG=en_US.UTF-8
export EDITOR='nano'

# Shortcuts
export C="/mnt/c/Users/oscar/"

alert() {
    powershell.exe "New-BurntToastNotification -Text \"$1\""
}
alias notify='alert'

# Allow privileged ports as privileged user
echo 'net.ipv4.ip_unprivileged_port_start=0' > /etc/sysctl.d/50-unprivileged-ports.conf

# Go Lang
# Sets environment varibles for golang
if [ -z "$GOPATH" ]; then
    export GOROOT="/usr/local/go"
    export GOPATH="$HOME/go"
    export PATH="$PATH:$GOPATH/bin:$GOROOT/bin"
fi

# Node Version Manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# XServer
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
export LIBGL_ALWAYS_INDIRECT=true

# Python
export PATH=$HOME/.local/bin:$PATH
